# Lab 1 - kwantowe

## Zadania
http://home.agh.edu.pl/~kzajac/dydakt/matp/lab1/kwantowe1.pdf

**Rozwiązania: Marcin Przewięźlikowski**

https://github.com/mprzewie/mwip_course

In [1]:
using LinearAlgebra
using QuantumInformation

#### **1. Pokazać, że wektory $(1,0,1,0)$, $(1,1,0,0)$, $(0,1,1,1)$, $(0,0,1,1)$ tworzą bazę w przestrzeni $R^4$**

Macierz stworzona przez złożenie tych wektorów to:

In [2]:
v1 = [1 0 1 0]
v2 = [1 1 0 0]
v3 = [0 1 1 1]
v4 = [0 0 1 1]

m = [v1; v2; v3; v4]

4×4 Array{Int64,2}:
 1  0  1  0
 1  1  0  0
 0  1  1  1
 0  0  1  1

Rząd tej macierzy wynosi: 

In [3]:
rank(m)

4

Z tego, że $rank(m) = 4$ można wywnioskować, że jest ona złożona z czterech liniowo niezależnych wektorów - a więc tworzących bazę przestrzeni $R^4$

#### **2. Przedstaw wektor $(2,0,-1,-2)$ jako kombinacje liniową wektorów bazy z p.1**

In [4]:
v5 = [2 0 -1 -2]
(v1 + v2 - v3 - v4) == v5

true

**3. Pokazać, że jeżeli przyjmiemy, ze stany pojedynczego bitu w komputerze klasycznym
$0$ reprezentujemy przez wektor $(1,0)$, a $1$ przez wektor $(0,1)$, to dzialanie operatora
NOT na danym bicie jest reprezentowane przez mnożenie macierzy $X = \sigma_x$ przez wektor
reprezentujący stan bitu.**

In [5]:
sigma_x = [ 
    [0 1]
    [1 0]
]

f = [1 0]
t = [0 1]

 f * sigma_x == t && t * sigma_x == f

true

**4. Pokaż że macierze jednostkowa i Pauliego sa liniowo niezależne w przestrzeni liniowej
macierzy 2x2 zarówno nad ciałem liczb rzeczywistych, jak i zespolonych.**

In [6]:
# jednostkowa
eye = [
    [1.0 0.0]
    [0.0 1.0]
]

# macierze Pauliego
sigma_1 =  [ 
    [0.0 1.0]
    [1.0 0.0]
]

sigma_2 = [
    [0.0 -1.0im]
    [1.0im 0.0]
]

sigma_3 = [
    [1.0 0.0]
    [0.0 -1.0]
]

# macierze jako 4-wymiarowe wektory
eye_v = reshape(eye, 1, 4)
sigma_1_v = reshape(sigma_1, 1, 4)
sigma_2_v = reshape(sigma_2, 1, 4)
sigma_3_v = reshape(sigma_3, 1, 4)

1×4 Array{Float64,2}:
 1.0  0.0  0.0  -1.0

Rząd macierzy stworzonej z tych wektorów:

In [7]:
# rzeczywiste:
rank(real([eye_v; sigma_1_v; sigma_2_v; sigma_3_v]))

3

Macierz ma rząd 3, czego można się było spodziewać, gdyż $\sigma_2$ w postaci rzeczywistej ma same zera. Pozostałe 3 macierze są liniowo niezależne.

In [8]:
# zespolone
rank(complex([eye_v; sigma_1_v; sigma_2_v; sigma_3_v]))

4

Macierz ma rząd 4 a zatem wktory ją tworzące są liniowo niezależne. 

**5. Hermitowskie sprzężenie macierzy**

In [9]:
A = transpose(reshape(Vector(1:9) * (1 + 1im), 3, 3))

3×3 Transpose{Complex{Int64},Array{Complex{Int64},2}}:
 1+1im  2+2im  3+3im
 4+4im  5+5im  6+6im
 7+7im  8+8im  9+9im

In [10]:
# sprzężenie hermitowskie
conj_trans(x) = conj(transpose(x));

In [11]:
conj_trans(A)

3×3 Array{Complex{Int64},2}:
 1-1im  4-4im  7-7im
 2-2im  5-5im  8-8im
 3-3im  6-6im  9-9im

**6. Wyjaśnić dlaczego macierze Pauliego są hermitowskie**

Macierze Pauliego są hermitowskie, gdyż są równe swoim sprzężeniom hermitowskim:

In [12]:
all([s == conj_trans(s) for s in [sigma_1, sigma_2, sigma_3]])

true

**Pokazać że
dowolna macierz hermitowska (dwuwymiarowa) może być przedstawiona jako kombinacja liniowa (skalary
rzeczywiste) macierzy jednostkowej i Pauliego.**

Dwuwymiarowe macierze hermitowskie mogą powstać z przekształcenia wektora z $R^3$ $(a_1, a_2, a_3)$:

$$ \begin{matrix}
a_1 & a_2 \\
\overline{a_2} & a_3 
\end{matrix}  $$
Są one zatem równoważne wektorom z przestrzeni $R^3$. 
Macierze jednostkowa i Pauliego w postaci takich wektorów to:

In [13]:
matrices_as_3_dim_vectors = [[s[1], s[2], s[4]] for s in [eye, sigma_1, sigma_2, sigma_3]]

4-element Array{Array{Complex{Float64},1},1}:
 [1.0+0.0im, 0.0+0.0im, 1.0+0.0im] 
 [0.0+0.0im, 1.0+0.0im, 0.0+0.0im] 
 [0.0+0.0im, 0.0+1.0im, 0.0+0.0im] 
 [1.0+0.0im, 0.0+0.0im, -1.0+0.0im]

In [14]:
rank(hcat(matrices_as_3_dim_vectors...))

3

Rząd macierzy powstałej z tych wektorów wynosi 3, a więc z powodzeniem można złożyć z nich dowolny wektor z $R^3$, a więc i każdą dwuwymiarową macierz Hermitowską.

**7. Przypomnienie. Policzyć iloczyn skalarny wektorów w R3 dla a = $(1, 2, 3)$,
b = $(3, 1, 4)$**

In [15]:
a = [1,2,3]
b = [3,1,4]
dot(a, b)

17

**8. Wektory o współrzędnych zespolonych. Notacja Diraca. Niech $\psi = (1 + i, 2 + 2i)$ oraz
$\phi = (3 + 3i, 4 + 4i)$**

In [16]:
psi = [1 + 1im, 2 + 2im]
phi = [3 + 3im, 4 + 4im];

* przedstawic reprezentację kolumnową $| \psi \rangle$

In [17]:
q(bra_or_ket_f, v) = sum(bra_or_ket_f(i, length(v)) * v[i] for i=1:length(v)) 

q (generic function with 1 method)

In [18]:
q(ket, psi)

2-element Array{Complex{Float64},1}:
 1.0 + 1.0im
 2.0 + 2.0im

* przedstawic reprezentacje wierszową $\langle \psi | $

In [19]:
q(bra, psi)

1×2 Adjoint{Complex{Float64},Array{Complex{Float64},1}}:
 1.0+1.0im  2.0+2.0im

* policzyć iloczyn skalarny $\langle \psi | \phi \rangle$

In [20]:
dot(q(bra, psi), q(ket, phi))

22.0 + 0.0im

* policzyć iloczyn skalarny $\langle \psi | \psi \rangle$

In [21]:
dot(q(bra,psi),  q(ket, psi))

10.0 + 0.0im

* policzyć norme (dlugość) $\psi$ zdefiniowana jako $\sqrt[2]{ \langle \psi | \psi \rangle}$

In [22]:
sqrt(dot(q(bra, psi), q(ket, psi)))

3.1622776601683795 + 0.0im

* przedstawić reprezentację macierzową operatora $| \psi \rangle \langle \phi | $

In [23]:
q(ket, psi) * q(bra, phi)

2×2 Array{Complex{Float64},2}:
 0.0+6.0im   0.0+8.0im 
 0.0+12.0im  0.0+16.0im

**9. Pokazać na macierzy liczb zespolonych:**

$$
A = \begin{bmatrix}
a & b \\
c & d 
\end{bmatrix} 
$$
oraz
$$\psi = (\alpha, \beta)$$
że $$(A | \psi \rangle)^T = \langle \psi | A^T$$

$$
(A | \psi \rangle)^T = 
\begin{bmatrix}
a\alpha +  b\beta \\
c\alpha +  d\beta
\end{bmatrix}^T = 
\begin{bmatrix}
a\alpha +  b\beta & 
c\alpha +  d\beta \\
\end{bmatrix} = 
$$

$$
\langle \psi | A^T = 
\langle \alpha \beta | \begin{bmatrix}
a & c \\
b & d 
\end{bmatrix} = 
\begin{bmatrix}
a\alpha +  b\beta & 
c\alpha +  d\beta \\
\end{bmatrix} 
$$

$$c.n.d$$



**10. Pokazać, że macierz unitarna nie zmienia długości wektora**

Czyli 

$$
A^TA = AA^T = 1 \implies || \psi || =  || A | \psi \rangle ||
$$

Niech $E$ będzie dwuwymiarową macierzą jednostkową. Wtedy: $$\forall_{\psi} \langle \psi | E = \psi \land  E| \psi \rangle = \psi$$

Zatem z **9**:
$$(|\psi \rangle)^T = \langle \psi | $$
i równoważnie
$$( \langle \psi |)^T =  |\psi \rangle $$

$ || A  |\psi \rangle || = \sqrt[2]{(A  |\psi \rangle)^T(A  |\psi \rangle)}  = \sqrt[2]{(\langle \psi | A^T)(A  |\psi \rangle)} = \sqrt[2]{(\langle \psi | A^TA  |\psi \rangle)} = \sqrt[2]{(\langle \psi | \psi \rangle)} = || \psi || $

$$c.n.d$$

**11. Pokazać że macierze Pauliego są unitarne.**

In [24]:
all([s * conj_trans(s) == eye for s in [sigma_1, sigma_2, sigma_3]])

true

**12. Iloczyn tensorowy wektorów. Niech $ \psi = (1 + i, 2 + 2i)$ oraz $\phi = (3 + 3i, 4 + 4i)$. Policzyć $|\psi\rangle \otimes |\phi\rangle$**

In [25]:
kron(q(ket, psi), q(ket, phi))

4-element Array{Complex{Float64},1}:
 0.0 + 6.0im 
 0.0 + 8.0im 
 0.0 + 12.0im
 0.0 + 16.0im

**13. Iloczyn tensorowy macierzy $A$ i $B$ to macierz $C$, że $A |\psi\rangle \otimes B\phi\rangle = C(|\psi\rangle \otimes |\phi\rangle)$. Użyć powyższej równości dla wektorów $\psi = (\alpha, \beta)$, $\phi = (\gamma, \delta)$ i znaleźć postać macierzową $X \otimes X$**.

$$
X = \begin{bmatrix}
a & b \\
c & d 
\end{bmatrix} 
$$

$$
X \otimes X =  
\begin{bmatrix}
aX & bX \\
cX & dX 
\end{bmatrix} = 
\begin{bmatrix}
aa & ab & ba & bb \\
ac & ad & bc & bd \\
ca & cb & da & db \\
cc & cd & dc & dd \\
\end{bmatrix}
$$