# lab2

Excercises: http://home.agh.edu.pl/~kzajac/dydakt/matp/lab2/zad2.pdf

In [1]:
from qiskit import QuantumCircuit, ClassicalRegister, QuantumRegister
from qiskit import execute
import numpy as np
from qiskit import BasicAer
backend = BasicAer.get_backend('statevector_simulator')


## example 1 

In [2]:
q1 = QuantumRegister(2)
circ1 = QuantumCircuit(q1)
circ1.h(q1[0])
circ1.ry(np.pi / 3, q1[1])
circ1.draw()

In [3]:
execute(circ1, backend).result().get_statevector(circ1)

array([0.61237244+0.j, 0.61237244+0.j, 0.35355339+0.j, 0.35355339+0.j])

## example 2

In [4]:
q2 = QuantumRegister(2)
circ2 = QuantumCircuit(q2)
circ2.initialize([0, 0, 1, 0], q2)
circ2.h(q2[0])
circ2.ry(np.pi / 3, q2[1])
circ2.draw()

In [5]:
execute(circ2, backend).result().get_statevector(circ2)

array([-0.35355339+0.j, -0.35355339+0.j,  0.61237244+0.j,  0.61237244+0.j])

## example 3

In [6]:
q3 = QuantumRegister(2)
circ3 = QuantumCircuit(q3)
circ3.initialize([0, 0, 1, 0], q3)
circ3.cx(q3[1], q3[0])
circ3.ry(np.pi/3, q3[1])
circ3.h(q3[0])
circ3.draw()

In [7]:
execute(circ3, backend).result().get_statevector(circ3)

array([-0.35355339+0.j,  0.35355339+0.j,  0.61237244+0.j, -0.61237244+0.j])

## example 4

In [8]:
q4 = QuantumRegister(2)
circ4 = QuantumCircuit(q4)
circ4.initialize([0, 0, 1, 0], q4)
circ4.ry(np.pi/3, q4[1])
circ4.h(q4[0])
circ4.cx(q4[1], q4[0])

circ4.draw()

In [9]:
execute(circ4, backend).result().get_statevector(circ4)

array([-0.35355339+0.j, -0.35355339+0.j,  0.61237244+0.j,  0.61237244+0.j])